package com.example.msadentistryclinic.models.enums;

public enum Tooth {
    CENTRAL_INCISOR_L_T, CENTRAL_INCISOR_R_T, LATERAL_INCISOR_L_T, LATERAL_INCISOR_R_T, CANINE_L_T, CANINE_R_T, FIRST_PREMOLAR_L_T, FIRST_PREMOLAR_R_T, SECOND_PREMOLAR_L_T, SECOND_PREMOLAR_R_T, FIRST_MOLAR_L_T, FIRST_MOLAR_R_T, SECOND_MOLAR_L_T, SECOND_MOLAR_R_T, THIRD_MOLAR_L_T, THIRD_MOLAR_R_T, CENTRAL_INCISOR_L_B, CENTRAL_INCISOR_R_B, LATERAL_INCISOR_L_B, LATERAL_INCISOR_R_B, CANINE_L_B, CANINE_R_B, FIRST_PREMOLAR_L_B, FIRST_PREMOLAR_R_B, SECOND_PREMOLAR_L_B, SECOND_PREMOLAR_R_B, FRIST_MOLAR_L_B, FRIST_MOLAR_R_B, SECOND_MOLAR_L_B, SECOND_MOLAR_R_B, THIRD_MOLAR_L_B, THIRD_MOLAR_R_B
}
