package com.example.clinicsystem.models.enums;

public enum MedicalAlert {
    ALLERGIES, HYPERTENSION, DIABETES, BLEEDING_DISORDERS, DRUGS, CARDIOVASCULAR_DISEASES, ANEMIA, ASTHMA, CANCER, BLOOD_PRESSURE
}
